// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum CreateChatRoom {
  NONE = 0,
  EXISTS_ROOM = 1,
  REQUIRED_ROOM_ID = 2
}
