// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ExitChatRoom {
  NONE = 0,
  ROOM_REMOVED = 1,
  NO_EXISTS_ROOM = 2,
  NOT_IN_ROOM = 3,
  FAILED_TO_EXIT = 4
}
