// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum PacketType {
  NONE = 0,
  CREATE_CHAT_ROOM = 1,
  UPDATE_CHAT_ROOM = 2,
  ENTER_CHAT_ROOM = 3,
  EXIT_CHAT_ROOM = 4
}
