// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class RoomId implements flatbuffers.IUnpackableObject<RoomIdT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoomId {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoomId(bb:flatbuffers.ByteBuffer, obj?:RoomId):RoomId {
  return (obj || new RoomId()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoomId(bb:flatbuffers.ByteBuffer, obj?:RoomId):RoomId {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoomId()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

idLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

idArray():Int8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Int8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static getFullyQualifiedName():string {
  return 'springBootChat.domain.RoomId';
}

static startRoomId(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static createIdVector(builder:flatbuffers.Builder, data:number[]|Int8Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createIdVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createIdVector(builder:flatbuffers.Builder, data:number[]|Int8Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startIdVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endRoomId(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRoomId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset):flatbuffers.Offset {
  RoomId.startRoomId(builder);
  RoomId.addId(builder, idOffset);
  return RoomId.endRoomId(builder);
}

unpack(): RoomIdT {
  return new RoomIdT(
    this.bb!.createScalarList<number>(this.id.bind(this), this.idLength())
  );
}


unpackTo(_o: RoomIdT): void {
  _o.id = this.bb!.createScalarList<number>(this.id.bind(this), this.idLength());
}
}

export class RoomIdT implements flatbuffers.IGeneratedObject {
constructor(
  public id: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = RoomId.createIdVector(builder, this.id);

  return RoomId.createRoomId(builder,
    id
  );
}
}
