// automatically generated by the FlatBuffers compiler, do not modify

export enum PacketType {
  NONE = 0,
  CREATE_CHAT_ROOM = 1,
  UPDATE_CHAT_ROOM = 2,
  ENTER_CHAT_ROOM = 3,
  EXIT_CHAT_ROOM = 4
}
