CREATE TABLE `oss` (
	`id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
	`os` VARCHAR(63) NOT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `uniq_os` (`os`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
