CREATE TABLE `visits` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`visitor` BIGINT(20) UNSIGNED NOT NULL,
	`host` TINYINT(3) UNSIGNED NOT NULL,
	`ip` INT(10) UNSIGNED NOT NULL,
	`parameter` INT(10) UNSIGNED NOT NULL,
	`path` INT(10) UNSIGNED NOT NULL,
	`scheme` TINYINT(1) UNSIGNED NOT NULL,
	`title` INT(10) UNSIGNED NOT NULL,
	`localTime` DATETIME(6) NOT NULL,
	`serverTime` DATETIME(6) NOT NULL DEFAULT current_timestamp(6),
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
